version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: audiofiler
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./config/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "${MYSQL_DB_PORT}:${MYSQL_DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL=${API_BASE_URL}
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - "${ADMINER_PORT}:${ADMINER_PORT}"
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db

