version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL=${API_BASE_URL}
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

